import { PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, Column } from 'typeorm';

/**
 * Base entity class that provides common fields for all entities
 * Includes audit fields (createdBy, updatedBy) and soft delete support
 * Note: id field is auto-generated by @PrimaryGeneratedColumn decorator
 */
export abstract class BaseEntity {
  @PrimaryGeneratedColumn()
  id!: number;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;

  @Column({ type: 'int', nullable: true })
  createdBy?: number;

  @Column({ type: 'int', nullable: true })
  updatedBy?: number;

  @Column({ type: 'timestamp', nullable: true })
  deletedAt?: Date;
}

